In [2]:
import pandas as pd 
dataset = pd.read_csv("Market_Basket_Analysis_v1.csv")
dataset

,Order Date,Order ID,Customer ID,Ship Mode,Description,Information,Customer Name,Segment,City,State,Country,Market,Region,Attribute,Item Name,Quantity,Product ID,Unit Price,Total Sales
0,31-01-2021 00:00,BU-2013-7380,MH-7455,Standard Class,BU-2013-7380MH-7455Mark Hamilton,MH-7455Mark HamiltonConsumerBurgasBurgas,Mark Hamilton,Consumer,Burgas,Burgas,Bulgaria,EMEA,Middle Eastern,Item name1,shrimp,167,10002439.0,74.69,12473.23
1,31-01-2021 00:00,BU-2013-7380,MH-7455,Standard Class,BU-2013-7380MH-7455Mark Hamilton,MH-7455Mark HamiltonConsumerBurgasBurgas,Mark Hamilton,Consumer,Burgas,Burgas,Bulgaria,EMEA,Middle Eastern,Item name2,almonds,278,10000353.0,15.28,4247.84
2,31-01-2021 00:00,BU-2013-7380,MH-7455,Standard Class,BU-2013-7380MH-7455Mark Hamilton,MH-7455Mark HamiltonConsumerBurgasBurgas,Mark Hamilton,Consumer,Burgas,Burgas,Bulgaria,EMEA,Middle Eastern,Item name3,avocado,324,10000994.0,46.33,15010.92
3,31-01-2021 00:00,BU-2013-7380,MH-7455,Standard Class,BU-2013-7380MH-7455Mark Hamilton,MH-7455Mark HamiltonConsumerBurgasBurgas,Mark Hamilton,Consumer,Burgas,Burgas,Bulgaria,EMEA,Middle Eastern,Item name4,vegetables mix,124,10000475.0,58.22,7219.28
4,31-01-2021 00:00,BU-2013-7380,MH-7455,Standard Class,BU-2013-7380MH-7455Mark Hamilton,MH-7455Mark HamiltonConsumerBurgasBurgas,Mark Hamilton,Consumer,Burgas,Burgas,Bulgaria,EMEA,Middle Eastern,Item name5,green grapes,680,10003338.0,86.31,58690.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72624,30-03-2023 00:00,US-2013-151225,GK-14620,Standard Class,US-2013-151225GK-14620Grace Kelly,GK-14620Grace KellyCorporateLimaLima (city),Grace Kelly,Corporate,Lima,Lima (city),Peru,LATAM,South,Item name1,chicken,290,10004883.0,86.72,25148.80
72625,30-03-2023 00:00,US-2013-151225,GK-14620,Standard Class,US-2013-151225GK-14620Grace Kelly,GK-14620Grace KellyCorporateLimaLima (city),Grace Kelly,Corporate,Lima,Lima (city),Peru,LATAM,South,Item name2,tropical fruit,314,10001990.0,56.47,17731.58
72626,30-03-2023 00:00,US-2013-151225,GK-14620,Standard Class,US-2013-151225GK-14620Grace Kelly,GK-14620Grace KellyCorporateLimaLima (city),Grace Kelly,Corporate,Lima,Lima (city),Peru,LATAM,South,Item name3,other vegetables,447,10000425.0,92.13,41182.11
72627,30-03-2023 00:00,US-2013-151225,GK-14620,Standard Class,US-2013-151225GK-14620Grace Kelly,GK-14620Grace KellyCorporateLimaLima (city),Grace Kelly,Corporate,Lima,Lima (city),Peru,LATAM,South,Item name4,vinegar,701,10001410.0,89.69,62872.69
72628,30-03-2023 00:00,US-2013-151225,GK-14620,Standard Class,US-2013-151225GK-14620Grace Kelly,GK-14620Grace KellyCorporateLimaLima (city),Grace Kelly,Corporate,Lima,Lima (city),Peru,LATAM,South,Item name5,shopping bags,2143,10000139.0,95.58,204827.94

In [3]:
df = pd.DataFrame(dataset)
df
product_set=df.groupby("Order ID")["Item Name"].apply(set).to_dict()
len(product_set)

15277

In [4]:
filter_basket = {key:value for key, value in product_set.items() if len(value)>1}
#print (filter_basket)
#final_basket=pd.DataFrame(filter_basket)
#final_basket
List_order_id=list(filter_basket.keys())
#print (List_order_id)
List_product_id=[list(values) for values in filter_basket.values()]
#print (List_product_id)
#final_basket
dict1={"Order_ID":List_order_id,"Product_ID":List_product_id}
#print(dict1)
df1=pd.DataFrame(dict1)
print(df1)

           Order_ID                                         Product_ID
0      AE-2013-1130  [green tea, ham, eggs, tomato juice, burgers, ...
1      AE-2013-1530  [cottage cheese, mushroom cream sauce, turkey,...
2      AE-2014-2840  [fruit/vegetable juice, sugar, baking powder, ...
3      AE-2014-4120                 [red/blush wine, other vegetables]
4      AG-2013-2840  [green tea, grated cheese, french fries, avocado]
...             ...                                                ...
12160  ZI-2014-6740  [canned fish, brown bread, newspapers, tropica...
12161  ZI-2014-6750                        [french fries, salad, eggs]
12162  ZI-2014-7160      [meat, whole milk, chicken, other vegetables]
12163  ZI-2014-9540  [curd, whole milk, whipped/sour cream, canned ...
12164  ZI-2014-9550                            [sugar, UHT-milk, soda]

[12165 rows x 2 columns]

In [30]:
unique_items = set(item for sublist in df1['Product_ID'] for item in sublist)
binary_matrix = []
for bought_together in df1['Product_ID']:
    binary_row = [ 1 if item in bought_together else 0 for  item in unique_items]
    binary_matrix.append(binary_row)
binary_df = pd.DataFrame(binary_matrix, columns = unique_items)
binary_df = pd.concat([df1['Order_ID'], binary_df], axis =1 )
print(binary_df)

ValueError: columns cannot be a set

In [5]:
# Create a list of unique items
unique_items = sorted(set(item for sublist in df1['Product_ID'] for item in sublist))
 
# Initialize an empty dictionary to hold binary values for each item
binary_data = {item: [] for item in unique_items}
 
# Iterate over each row in the original DataFrame
for bought_together in df1['Product_ID']:
    # Initialize a binary row for the current transaction
    binary_row = {item: 0 for item in unique_items}
    # Set the value to 1 if the item was bought in the transaction
    for item in bought_together:
        binary_row[item] = 1
    # Append the binary row to the binary_data dictionary
    for item, value in binary_row.items():
        binary_data[item].append(value)
 
# Create a DataFrame from the dictionary
binary_df = pd.DataFrame(binary_data)
 
# Concatenate with the original DataFrame
binary_df2 = pd.concat([df1['Order_ID'], binary_df], axis=1)
 
# Display the binary DataFrame
print(binary_df)

       Instant food products  UHT-milk  abrasive cleaner  almonds  \
0                          0         0                 0        0
1                          0         0                 0        0
2                          0         0                 0        0
3                          0         0                 0        0
4                          0         0                 0        0
...                      ...       ...               ...      ...
12160                      0         0                 0        0
12161                      0         0                 0        0
12162                      0         0                 0        0
12163                      0         0                 0        0
12164                      0         1                 0        0

       antioxydant juice  artif. sweetener  asparagus  avocado  babies food  \
0                      0                 0          0        0            0
1                      0                 0          0        0            0
2                      0                 0          0        0            0
3                      0                 0          0        0            0
4                      0                 0          0        1            0
...                  ...               ...        ...      ...          ...
12160                  0                 0          0        0            0
12161                  0                 0          0        0            0
12162                  0                 0          0        0            0
12163                  0                 0          0        0            0
12164                  0                 0          0        0            0

       baby cosmetics  ...  white wine  whole milk  whole weat flour  \
0                   0  ...           0           0                 0
1                   0  ...           0           0                 0
2                   0  ...           0           0                 0
3                   0  ...           0           0                 0
4                   0  ...           0           0                 0
...               ...  ...         ...         ...               ...
12160               0  ...           0           0                 0
12161               0  ...           0           0                 0
12162               0  ...           0           1                 0
12163               0  ...           0           1                 0
12164               0  ...           0           0                 0

       whole wheat pasta  whole wheat rice  yams  yogurt  yogurt cake  \
0                      0                 0     0       0            0
1                      0                 0     0       0            0
2                      0                 0     0       1            0
3                      0                 0     0       0            0
4                      0                 0     0       0            0
...                  ...               ...   ...     ...          ...
12160                  0                 0     0       1            0
12161                  0                 0     0       0            0
12162                  0                 0     0       0            0
12163                  0                 0     0       1            0
12164                  0                 0     0       0            0

       zucchini  zwieback
0             0         0
1             0         0
2             0         0
3             0         0
4             0         0
...         ...       ...
12160         0         0
12161         0         0
12162         0         0
12163         0         0
12164         0         0

[12165 rows x 269 columns]

In [6]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import pandas as pd
# Load your dataset
data = binary_df
# Preprocess the data (if necessary)
# Encode the data
# Assuming your dataset has already been properly encoded and formatted
# Apply Apriori algorithm to find frequent itemsets
frequent_itemsets = apriori(data, min_support=0.01, use_colnames=True)
# Generate association rules
#rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
# Filter rules based on desired metrics
#filtered_rules = rules[(rules['confidence'] > 0.5) & (rules['lift'] > 1.2)]
#
# # Print the filtered rules
# print(filtered_rules)
# # Assuming you have already generated and filtered association rules
# # filtered_rules = ...
# # Sort the rules by lift to prioritize the most impactful ones
# sorted_rules = filtered_rules.sort_values(by='lift', ascending=False)
# # Iterate through the sorted rules and take action
# for index, rule in sorted_rules.iterrows():
#     antecedents = rule['antecedents']
#     consequents = rule['consequents']
#     lift = rule['lift']
#     # Example action: Print out the rule and suggest a cross-selling strategy
#     print(f"Rule: {antecedents} -> {consequents}, Lift: {lift}")
#     print("Suggested Action: Promote the purchase of", consequents, "when customers buy", antecedents)
#     print("---")#
print(frequent_itemsets)

C:\Users\10710602\AppData\Roaming\Python\Python312\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                                       itemsets
0    0.026223                                     (UHT-milk)
1    0.012495                                      (almonds)
2    0.020140                                      (avocado)
3    0.013975                                (baking powder)
4    0.040855                                         (beef)
..        ...                                            ...
398  0.011097      (rolls/buns, whole milk, root vegetables)
399  0.013646               (rolls/buns, whole milk, yogurt)
400  0.010111  (whole milk, tropical fruit, root vegetables)
401  0.012495          (whole milk, yogurt, root vegetables)
402  0.012906           (whole milk, yogurt, tropical fruit)

[403 rows x 2 columns]

In [7]:
# Generate association rules
rules = association_rules(frequent_itemsets, metric="support", min_threshold=0.01)
# Filter rules based on desired metrics
#rules
filtered_rules = pd.DataFrame(rules[(rules['confidence'] > 0.01) & (rules['lift'] > 0.05)])
#
# # Print the filtered rules
print(filtered_rules)

                      antecedents                   consequents  \
0                          (beef)            (other vegetables)
1              (other vegetables)                        (beef)
2                          (beef)                  (rolls/buns)
3                    (rolls/buns)                        (beef)
4                          (beef)             (root vegetables)
..                            ...                           ...
629  (whole milk, tropical fruit)                      (yogurt)
630      (yogurt, tropical fruit)                  (whole milk)
631                  (whole milk)      (yogurt, tropical fruit)
632                      (yogurt)  (whole milk, tropical fruit)
633              (tropical fruit)          (whole milk, yogurt)

     antecedent support  consequent support   support  confidence      lift  \
0              0.040855            0.150760  0.016441    0.402414  2.669232
1              0.150760            0.040855  0.016441    0.109051  2.669232
2              0.040855            0.140567  0.011508    0.281690  2.003954
3              0.140567            0.040855  0.011508    0.081871  2.003954
4              0.040855            0.086067  0.014386    0.352113  4.091166
..                  ...                 ...       ...         ...       ...
629            0.035347            0.109248  0.012906    0.365116  3.342091
630            0.024003            0.195890  0.012906    0.537671  2.744763
631            0.195890            0.024003  0.012906    0.065883  2.744763
632            0.109248            0.035347  0.012906    0.118134  3.342091
633            0.082861            0.046691  0.012906    0.155754  3.335822

     leverage  conviction  zhangs_metric
0    0.010281    1.421118       0.651998
1    0.010281    1.076544       0.736377
2    0.005766    1.196465       0.522326
3    0.005766    1.044674       0.582927
4    0.010869    1.410636       0.787755
..        ...         ...            ...
629  0.009044    1.403016       0.726465
630  0.008204    1.739260       0.651303
631  0.008204    1.044834       0.790526
632  0.009044    1.093877       0.786735
633  0.009037    1.129183       0.763487

[634 rows x 10 columns]

In [8]:
#binary_df.to_csv('market_bast.csv')
#rules.to_csv('rules.csv')
#filtered_rules.to_csv('filtered_rules_final.csv')
filtered_rules.to_excel('filtered_rules_excel.xlsx')
#frequent_itemsets.to_csv('frequent_itemsets.csv')

C:\Users\10710602\AppData\Roaming\Python\Python312\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
C:\Users\10710602\AppData\Roaming\Python\Python312\site-packages\openpyxl\writer\excel.py:292: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  workbook.properties.modified = datetime.datetime.utcnow()

In [21]:
import pandas as pd 
dataset2 = pd.read_csv("filtered_rules_final.csv")
#df1
dataset2

,Unnamed: 0,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,0,other vegetables,beef,0.150760,0.040855,0.016441,0.109051,2.669232,0.010281,1.076544,0.736377
1,1,beef,other vegetables,0.040855,0.150760,0.016441,0.402414,2.669232,0.010281,1.421118,0.651998
2,2,rolls/buns,beef,0.140567,0.040855,0.011508,0.081871,2.003954,0.005766,1.044674,0.582927
3,3,beef,rolls/buns,0.040855,0.140567,0.011508,0.281690,2.003954,0.005766,1.196465,0.522326
4,4,beef,root vegetables,0.040855,0.086067,0.014386,0.352113,4.091166,0.010869,1.410636,0.787755
...,...,...,...,...,...,...,...,...,...,...,...
629,629,yogurt,whole milk,0.024003,0.195890,0.012906,0.537671,2.744763,0.008204,1.739260,0.651303
630,630,whole milk,yogurt,0.035347,0.109248,0.012906,0.365116,3.342091,0.009044,1.403016,0.726465
631,631,yogurt,whole milk,0.109248,0.035347,0.012906,0.118134,3.342091,0.009044,1.093877,0.786735
632,632,whole milk,yogurt,0.195890,0.024003,0.012906,0.065883,2.744763,0.008204,1.044834,0.790526
633,633,tropical fruit,yogurt,0.082861,0.046691,0.012906,0.155754,3.335822,0.009037,1.129183,0.763487

In [25]:
len(dataset2)

634

In [30]:
#dataset2['Order IDs'] = 
Order_ID_list = [[] for _ in range(634)]
for i in range (len(dataset2)):
   for j in range(len(df1)):
      if dataset2['antecedents'][i] in df1['Product_ID'][j] and dataset2['consequents'][i] in df1['Product_ID'][j]:
         Order_ID_list[i].append(df1['Order_ID'][j])

In [69]:
len(Order_ID_list)

634

In [82]:
dataset2['Order_ID'] = None
final_dataset = pd.DataFrame(columns = list(dataset2.columns))
#print(len(final_dataset))
#print(final_dataset[0][0])
for i in range (634):
    for j in range(len(Order_ID_list[i])):
        #print('before', len(final_dataset))
        final_dataset.loc[len(final_dataset)] = dataset2.iloc[i]
        final_dataset.loc[len(final_dataset)-1, 'Order_ID'] = Order_ID_list[i][j] 
        #print('after', len(final_dataset))

final_dataset

,Unnamed: 0,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric,Order_ID
0,0,other vegetables,beef,0.15076,0.040855,0.016441,0.109051,2.669232,0.010281,1.076544,0.736377,BN-2014-5090
1,0,other vegetables,beef,0.15076,0.040855,0.016441,0.109051,2.669232,0.010281,1.076544,0.736377,BU-2014-9730
2,0,other vegetables,beef,0.15076,0.040855,0.016441,0.109051,2.669232,0.010281,1.076544,0.736377,CA-2013-1140
3,0,other vegetables,beef,0.15076,0.040855,0.016441,0.109051,2.669232,0.010281,1.076544,0.736377,CA-2013-121755
4,0,other vegetables,beef,0.15076,0.040855,0.016441,0.109051,2.669232,0.010281,1.076544,0.736377,CA-2013-129903
...,...,...,...,...,...,...,...,...,...,...,...,...
162499,633,tropical fruit,yogurt,0.082861,0.046691,0.012906,0.155754,3.335822,0.009037,1.129183,0.763487,US-2014-168200
162500,633,tropical fruit,yogurt,0.082861,0.046691,0.012906,0.155754,3.335822,0.009037,1.129183,0.763487,US-2014-169936
162501,633,tropical fruit,yogurt,0.082861,0.046691,0.012906,0.155754,3.335822,0.009037,1.129183,0.763487,UZ-2014-8910
162502,633,tropical fruit,yogurt,0.082861,0.046691,0.012906,0.155754,3.335822,0.009037,1.129183,0.763487,ZA-2014-7540
162503,633,tropical fruit,yogurt,0.082861,0.046691,0.012906,0.155754,3.335822,0.009037,1.129183,0.763487,ZI-2014-6740

In [75]:
for i in range (100,200):
    for j in range(len(Order_ID_list[i])):
        final_dataset.loc[len(final_dataset)] = dataset2.iloc[i]
        final_dataset.loc[len(final_dataset), 'Order_ID'] = Order_ID_list[i][j] 

final_dataset

KeyboardInterrupt:

In [ ]:
for i in range (200,300):
    for j in range(len(Order_ID_list[i])):
        final_dataset.loc[len(final_dataset)] = dataset2.iloc[i]
        final_dataset.loc[len(final_dataset), 'Order_ID'] = Order_ID_list[i][j] 

final_dataset

In [ ]:
for i in range (300,400):
    for j in range(len(Order_ID_list[i])):
        final_dataset.loc[len(final_dataset)] = dataset2.iloc[i]
        final_dataset.loc[len(final_dataset), 'Order_ID'] = Order_ID_list[i][j] 

final_dataset

In [ ]:
for i in range (400,500):
    for j in range(len(Order_ID_list[i])):
        final_dataset.loc[len(final_dataset)] = dataset2.iloc[i]
        final_dataset.loc[len(final_dataset), 'Order_ID'] = Order_ID_list[i][j] 

final_dataset

In [ ]:
for i in range (500,634):
    for j in range(len(Order_ID_list[i])):
        final_dataset.loc[len(final_dataset)] = dataset2.iloc[i]
        final_dataset.loc[len(final_dataset), 'Order_ID'] = Order_ID_list[i][j] 

final_dataset

In [34]:
dataframe1 = pd.DataFrame(Order_ID_list)
dataframe1

dataframe1.to_csv('Order-list.csv')

In [35]:

final_dataset.to_csv('final_dataset.csv')

In [37]:
name = input ("please enter name")